import type { Metadata } from "next";

// fonts
import {Inter} from 'next/font/google'

const inter = Inter({
  subsets : ['latin'],
  variable : '--font-inter'
})

// components
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"


// style
import "@/style/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon : '/assets/icons/logo.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className}`}>
      <body>
        <Navbar/>
        <main>
        {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}
